#!/usr/bin/env bash

set -e

IMAGE_NAME="$1"

# IMAGE_NAME is "./debian_7.Dockerfile"
# strip basename
# strip leading "./"
# strip trailing ".Dockerfile"
IMAGE_DIR=$(dirname ${IMAGE_NAME})
NAME="$(printf $IMAGE_NAME | sed 's/\.\///' | sed 's/\.Dockerfile$//')"

cd $IMAGE_DIR
echo Docker building ${NAME}
$SUDO docker build --build-arg=GOLANG_VERSION=${GOLANG_VERSION} --build-arg=GOLANG_SHA256=${GOLANG_SHA256} --build-arg=GOLANG_ARCH=${GOLANG_ARCH} --platform "$GOLANG_ARCH" -t gitlfs/build-dockers:${NAME} -f "$NAME.Dockerfile" .
